### ISSUE TITLE
GAP standard tests do not work with loops 3.4.0

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/loops#2]
On a fresh install (stable-4.9 branch and packages installed via
```
make bootstrap-pkg-full
cd pkg
../bin/BuildPackages.sh
```
and loops replaced by its 3.4.0 archive from http://www.cs.du.edu/~petr/loops/ ) running ` make testinstall` results in diffs with all packages loaded:
```
testing: /circa/home/alexk/scratch/gap-stable/tst/testinstall/sylowhall.tst
########> Diff in /circa/home/alexk/scratch/gap-stable/tst/testinstall/sylowha\
ll.tst:6
# Input is:
IdGroup(SylowSubgroup(G, 3));
# Expected output:
[ 81, 7 ]
# But found:
Error, List Element: <list>[1] must have an assigned value
########
########> Diff in /circa/home/alexk/scratch/gap-stable/tst/testinstall/sylowha\
ll.tst:16
# Input is:
fine := true;; for p in PrimeDivisors(Size(G)) do fine := fine and HasHallSubg\
roup(G, [p]); od; fine;
# Expected output:
true
# But found:
false
########
```
I was initially unable to reproduce this, until I have figured out that one should load LOOPS first and after that load RCWA. It does not happen the other way round. If RCWA is loaded after LOOPS, then
```
G := GL(3,4);; SylowSubgroup(G, 3);
```
results in the following error message:
```
gap> G := GL(3,4);; SylowSubgroup(G, 3);
Error, List Element: <list>[1] must have an assigned value in
  return WreathProductInfo( W ).embeddings[i]; at /circa/home/alexk/scratch/gap-stable/pkg/rcwa-4.6.1/lib/rcwagrp.gi:2794 called from 
Embedding( wr, i ) at /circa/home/alexk/scratch/gap-stable/grp/basicmat.gi:363 called from
func( C[i] ) at /circa/home/alexk/scratch/gap-stable/lib/coll.gi:746 called from
List( [ 1 .. m + 1 ], function ( i )
      return Image( Embedding( wr, i ), SylowSubgroup( Source( Embedding( wr, i ) ), p ) );
  end ) at /circa/home/alexk/scratch/gap-stable/grp/basicmat.gi:363 called from
SylowSubgroupOfWreathProduct( k, Int( n / k ), p ) at /circa/home/alexk/scratch/gap-stable/grp/basicmat.gi:532 called from
<compiled statement>  called from
...  at *stdin*:9
you can 'return;' after assigning a value
brk>
```
@Stefan-Kohl do you have any insights on this?

The 2nd diff is probably the result of corrupted data after the 1st error.

**Comment by Stefan-Kohl** [comment]
No idea. -- With GAP 4.9.0 and loops 3.3.0, I cannot reproduce the problem. My vague guess is that the new version of loops causes the WreathProductInfo to be corrupted in some way -- so I'd suggest to look at what has changed between loops 3.3.0 and loops 3.4.0.

**Comment by olexandr-konovalov** [comment]
Past releases were imported when this repository has been created, so the difference between these two releases can be seen as a single commit here: https://github.com/gap-packages/loops/commit/9a8eede80316efccf54f9a360e3b4c6dea5a022d

In the meantime, `make teststandard` also completed, and I am attaching here the test log from that test. Some of the diffs look familiar, some not: see [teststandard2_2018-04-30-14-56.log](https://github.com/gap-packages/loops/files/1962338/teststandard2_2018-04-30-14-56.log)

**Comment by nagygp** [comment]
It seems that the problem is with the method selection for the Embedding command.

Please have a look at the output of the commands:

############################
LoadPackage("rcwa",false);
s4:=SymmetricGroup(4);
s3:=SymmetricGroup(3);
TraceMethods([WreathProduct,Embedding]);
wr:=WreathProduct(s4,s3);
Embedding(wr,1);
############################

Without preloading LOOPS 3.4:

############################
gap> LoadPackage("rcwa",false);
true
gap> s4:=SymmetricGroup(4);
Sym( [ 1 .. 4 ] )
gap> s3:=SymmetricGroup(3);
Sym( [ 1 .. 3 ] )
gap> TraceMethods([WreathProduct,Embedding]);
gap> wr:=WreathProduct(s4,s3);
#I  WreathProduct: permgroups: imprimitive at /opt/gap4/lib/gprdperm.gi:539
<permutation group of size 82944 with 8 generators>
gap> Embedding(wr,1);
#I  Embedding: perm wreath product at /opt/gap4/lib/gprdperm.gi:693
1st embedding into Group( [ (1,2,3,4), (1,2), (5,6,7,8), (5,6), ( 9,10,11,12), ( 9,10), ( 1, 5, 9)( 2, 6,10)( 3, 7,11)( 4, 8,12), 
  ( 1, 5)( 2, 6)( 3, 7)( 4, 8) ] )
############################

With preloaded LOOPS 3.4

############################
gap> LoadPackage("loops",false);
true
gap> LoadPackage("rcwa",false);
#I  method installed for IsNormalOp matches more than one declaration
#I  method installed for NormalClosure matches more than one declaration
#I  method installed for Exponent matches more than one declaration
true
gap> s4:=SymmetricGroup(4);
Sym( [ 1 .. 4 ] )
gap> s3:=SymmetricGroup(3);
Sym( [ 1 .. 3 ] )
gap> TraceMethods([WreathProduct,Embedding]);
gap> wr:=WreathProduct(s4,s3);
#I  WreathProduct: permgroups: imprimitive at /opt/gap4/lib/gprdperm.gi:539
<permutation group of size 82944 with 8 generators>
gap> Embedding(wr,1);
#I  Embedding: for a wreath product and 1 or 2 (RCWA) at /opt/gap4/pkg/rcwa-4.6.1/lib/rcwagrp.gi:2792
Error, List Element: <list>[1] must have an assigned value in
  return WreathProductInfo( W ).embeddings[i]; at /opt/gap4/pkg/rcwa-4.6.1/lib/rcwagrp.gi:2794 called from 
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:7
you can 'return;' after assigning a value
brk> 
############################

In neither version of LOOPS do we touch WreathProduct or Embedding.

**Comment by olexandr-konovalov** [comment]
Thanks @nagygp for the example. So, we see that loading LOOPS before RCWA triggers selection of a different method. At the moment, I still don't know if this is a LOOPS or RCWA problem, or even anything else. But at least we have a simple example.

Also, what happens to this example if you run it with no packages, and with LOOPS but without RCWA?

**Comment by nagygp** [comment]
Dear @Stefan-Kohl and @alex-konovalov.

While I am not claiming that this is an RCWA problem, it seems to me that a rather logical change in RCWA code would solve the problem.

This is from rcwagrp.gi:

```
############################################################################
##
#M  Embedding( <W>, <i> ) . . . . . . . . . . for a wreath product and 1 or 2
##
InstallMethod( Embedding,
               "for a wreath product and 1 or 2 (RCWA)",
               ReturnTrue, [ HasWreathProductInfo, IsPosInt ], 0,

  function ( W, i )
#NG#    if not i in [1,2] then TryNextMethod(); fi;
    if (not i in [1,2]) or (Length(WreathProductInfo(W).embeddings)<2) then TryNextMethod(); fi;
    return WreathProductInfo(W).embeddings[i];
  end );
```
I run `TestPackage("rcwa")` and it seems to be OK. 

Of course, Stefan must have a closer look.

Thanks, 

Gabor

**Comment by olexandr-konovalov** [comment]
Thanks @nagygp. It will be useful for a reader to see the diffs, so I am pasting here the current version of RCWA code:
```
  function ( W, i )
    if not i in [1,2] then TryNextMethod(); fi;
    return WreathProductInfo(W).embeddings[i];
  end );
``` 
This code assumes that if `HasWreathProductInfo` holds, then `embeddings` component has the _i_-th entry. However, as I can see in the library code at
https://github.com/gap-system/gap/blob/242849c48a4e23509c1e1d328aa5960dadd6f6d7/lib/gprdperm.gi#L690 
that's not necessarily the case. The same holds in https://github.com/gap-system/gap/blob/97ce29571693418b171b60c98689070aaca0db2d/lib/gprd.gi#L995. 

The code in the library methods also uses a more precise check, and I suggest that if we proceed with @nagygp's suggestion, then one should check for `IsBound( WreathProductInfo(W).embeddings[i]`) instead of checking its length.

But actually with those two methods in the library I don't see why RCWA needs to install its own method for embedding - perhaps @Stefan-Kohl could explain?

**Comment by Stefan-Kohl** [comment]
Probably there was a reason for adding this method, at least at the time when I have written that code -- but I don't remember the details. If all tests and all manual examples still work when removing that method (did you check this?), then it is likely not needed any more, and can be removed.

**Comment by olexandr-konovalov** [comment]
@Stefan-Kohl Removing it completely causes problems (see https://travis-ci.org/gap-packages/rcwa/builds/394978730). Either method selection fails because some filter is missing, or the method should stay but be updates as suggested above. Will edit my PR - at any case, a soon RCWA release must be anticipated.

**Comment by Stefan-Kohl** [comment]
It seems that the (undocumented) filter `IsWreathProductElementCollection' is missing -- so maybe that should be set when creating the wreath product, to allow the method being removed.

**Comment by olexandr-konovalov** [comment]
Yes, let's continue discussion at https://github.com/gap-packages/rcwa/pull/2/

Perhaps @nagygp could then help us to test if this will fix the issue from above.

**Comment by olexandr-konovalov** [comment]
... and if so, we may have new LOOPS in GAP 4.9.2, provided we will be able to release RCWA very quickly.

**Comment by nagygp** [comment]
I am not an expert in the new testing frameworks, but I cannot reproduce the original errors with the @alex-konovalov 's fix. :-)

In other words, to me, the problem seems to be solved. 

I am sooo happy with this, thanks for both of you!

**Comment by olexandr-konovalov** [comment]
New RCWA release is now in preparation - see https://github.com/gap-packages/rcwa/pull/4

**Comment by olexandr-konovalov** [comment]
Good new - after new RCWA release has been picked up, I've enabled latest LOOPS in https://github.com/gap-system/gap-distribution/commit/00ce550782960fc97df58b1785684084d1721daf and it does not break tests any more. I am closing this issue now, hopefully there will be no need to reopen it.

**Comment by nagygp** [comment]
Thanks once more, @alex-konovalov!
