### ISSUE TITLE
Test failures in the GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/loops#4]
In the master branch there is a different failure with the latest release of LOOPS, see https://travis-ci.org/gap-system/gap-docker-pkg-tests-master-staging/jobs/416920133 : when all packages are loaded, I see a long list of
```
  Error, Function: number of arguments must be 2 (not 1) in
  Error, Function: number of arguments must be 2 (not 1) in
  Error, Function: number of arguments must be 2 (not 1) in
  Error, Function: number of arguments must be 2 (not 1) in
...
```
lines. Is this something you can observe with the development version of LOOPS too?

**Comment by nagygp** [comment]
In the Travis output, the very first line of the error message is `Error, Record Element: '<rec>.pi' must have an assigned value in`. 

Therefore this issue seems to be related to #3; both complain about the missing <pi> field of some record. 

I think I understand the situation now. Again, LOOPS seems to confuse the method selection for FR. 

While I am not claiming FR is broken, I think they can fix this. 

I opened issue https://github.com/gap-packages/fr/issues/28#issue-353266414 on FR's github page. 

There, I explain the situation more in details and suggest a possible solution.

**Comment by olexandr-konovalov** [comment]
Loops tests now pass in GAP master branch https://travis-ci.org/gap-system/gap-docker-pkg-tests-master-staging/jobs/453340437
